# This workflow will install Python dependencies, run tests and lint with a single version of Python
# Test 

name: Create test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Change files infos
      run: |
        echo "Student,class" > flussi/students.csv
        echo "165730,1AI" >> flussi/students.csv
        echo "165731,1AI" >> flussi/students.csv
        echo "165732,1AI" >> flussi/students.csv
        echo "165733,1AI" >> flussi/students.csv
        echo "165734,1AI" >> flussi/students.csv
        echo "165735,1AI" >> flussi/students.csv
        echo "165736,1AI" >> flussi/students.csv
        echo "165737,1AI" >> flussi/students.csv
        echo "165738,1AI" >> flussi/students.csv
        echo "165739,1AI" >> flussi/students.csv
        echo "1657310,1AI" >> flussi/students.csv
        echo "1657311,1AI" >> flussi/students.csv
        echo "1657312,1AI" >> flussi/students.csv
        echo "1657313,1AI" >> flussi/students.csv
        echo "1657314,1AI" >> flussi/students.csv
        echo "1657315,1AI" >> flussi/students.csv
        echo "1657316,1AI" >> flussi/students.csv
        echo "1657317,1AI" >> flussi/students.csv
        echo "1657318,1AI" >> flussi/students.csv
        echo "1657319,1AI" >> flussi/students.csv
        echo "1657320,1AI" >> flussi/students.csv
        echo "1657321,1AI" >> flussi/students.csv
        echo "1657322,1AI" >> flussi/students.csv
        echo "Emails" >> flussi/teachers.csv
        echo  ${{ secrets.TOCKEN }}
    - name: Test
      run: |
        python ./bin/test_school_repo.py ${{ secrets.TOCKEN }}
